# Generated by Django 6.0 on 2025-12-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_likecount"),
    ]

    operations = [
        migrations.AddField(
            model_name="likecount",
            name="liked",
            field=models.BooleanField(default=False),
        ),
    ]
